const scripts = {
	"on_load-main_menu": [
	  {
		action: "MUTATE_VARIABLE",
		variable: "current-chapter",
		operation: "SET",
		value: 0,
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "colors",
		script: "command-colors",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "colors",
		argument: "bg",
		script: "command-colors-bg",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "colors",
		argument: "bold",
		script: "command-colors-bold",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "colors",
		argument: "dim",
		script: "command-colors-dim",
	  },
	  {
		action: "CHECK_DEBUG_MODE",
		expected_bool: true,
		jump_index: 7,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 99,
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "debug",
		script: "debug",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "hub",
		script: "debug-hub",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "honk",
		script: "system_bell",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "bob",
		script: "debug-bob",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "bob2",
		script: "debug-bob2",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "bob3",
		script: "debug-bob3",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "simon",
		script: "debug-menu-simon",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "king",
		script: "debug-king",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "ch2",
		script: "menu-chapter_select-2",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "rtfm",
		script: "command-rtfm",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "buffer",
		argument: "test",
		script: "debug-buffertest",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "boot",
		script: "ch2-bootup",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "post",
		script: "debug-post",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "skip",
		argument: "1",
		script: "debug-jump-to-round1",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "skip",
		argument: "2",
		script: "debug-jump-to-round2",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "skip",
		argument: "3",
		script: "debug-jump-to-round3",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "skip",
		argument: "4",
		script: "debug-jump-to-round4",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "warp",
		script: "command-warp",
	  },
	  {
		is_fail: true,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "warp",
		script: "warp-fail",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "man",
		argument: "warp",
		script: "man-warp",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "1",
		script: "warp-ch2-1",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "11",
		script: "warp-ch2-11",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "12",
		script: "warp-ch2-12",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "13",
		script: "warp-ch2-13",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "14",
		script: "warp-ch2-14",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "21",
		script: "warp-ch2-21",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "22",
		script: "warp-ch2-22",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "23",
		script: "warp-ch2-23",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "31",
		script: "warp-ch2-31",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "32",
		script: "warp-ch2-32",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "33",
		script: "warp-ch2-33",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "34",
		script: "warp-ch2-34",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "99",
		script: "warp-ch2-99",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle exterior",
		script: "warp-ch2-castle-exterior",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle entrance",
		script: "warp-ch2-1",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle hallway front",
		script: "warp-ch2-11",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle hallway back",
		script: "warp-ch2-12",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle throne room",
		script: "warp-ch2-13",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "throne room",
		script: "warp-ch2-13",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle bedroom",
		script: "warp-ch2-14",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "gibson's bedroom",
		script: "warp-ch2-14",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "gibsons bedroom",
		script: "warp-ch2-14",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "gibson bedroom",
		script: "warp-ch2-14",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "king gibson's bedroom",
		script: "warp-ch2-14",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "king gibsons bedroom",
		script: "warp-ch2-14",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "king gibson bedroom",
		script: "warp-ch2-14",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "workshop",
		script: "warp-ch2-21",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "server room",
		script: "warp-ch2-22",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "power plant",
		script: "warp-ch2-23",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "grand hall",
		script: "warp-ch2-31",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle hall",
		script: "warp-ch2-31",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle kitchen",
		script: "warp-ch2-32",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "hydroponics",
		script: "warp-ch2-33",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle hydroponics",
		script: "warp-ch2-33",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "hydroponics room",
		script: "warp-ch2-33",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "castle pantry",
		script: "warp-ch2-34",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "secret lab",
		script: "warp-ch2-99",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "town",
		script: "warp-ch2-town",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "bakery",
		script: "warp-ch2-bakery",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "greenhouse",
		script: "warp-ch2-greenhouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "wopr room",
		script: "warp-ch2-wopr",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "wopr",
		script: "warp-ch2-wopr",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "library",
		script: "warp-ch2-library",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "lodge",
		script: "warp-ch2-library",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "inner sanctum",
		script: "warp-ch2-rtfmroom",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "rtfm room",
		script: "warp-ch2-rtfmroom",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "rtfm",
		script: "warp-ch2-rtfmroom",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "home",
		script: "warp-ch2-magehouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "my home",
		script: "warp-ch2-magehouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "my house",
		script: "warp-ch2-magehouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "bobsclub",
		script: "warp-ch2-bobsclub",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "bobs club",
		script: "warp-ch2-bobsclub",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "bob's club",
		script: "warp-ch2-bobsclub",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "bobs club basement",
		script: "warp-ch2-bobsclub-basement",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "bob's club basement",
		script: "warp-ch2-bobsclub-basement",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "beatrice's house",
		script: "warp-ch2-oldcouplehouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "beatrices house",
		script: "warp-ch2-oldcouplehouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "beatrice house",
		script: "warp-ch2-oldcouplehouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "bea",
		script: "warp-ch2-oldcouplehouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "smith's house",
		script: "warp-ch2-smithfamily",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "smiths house",
		script: "warp-ch2-smithfamily",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "smith house",
		script: "warp-ch2-smithfamily",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "warp",
		argument: "smith",
		script: "warp-ch2-smithfamily",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "storyflag",
		script: "ch2-debug-storyflag",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "storyflag",
		argument: "0",
		script: "debug-map-flags-for-round0",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "storyflag",
		argument: "1",
		script: "debug-map-flags-for-round1",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "storyflag",
		argument: "2",
		script: "debug-map-flags-for-round2",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "storyflag",
		argument: "3",
		script: "debug-map-flags-for-round3",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "storyflag",
		argument: "4",
		script: "debug-map-flags-for-round4",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "storyflag",
		argument: "5",
		script: "debug-map-flags-for-round5",
	  },
	  {
		action: "SHOW_SERIAL_DIALOG",
		disable_newline: false,
		serial_dialog: "main_menu.mgs:39:3",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 99,
	  },
	],
	"debug-post": [
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-wizard-backstory",
		bool_value: true,
	  },
	  {
		action: "SET_SERIAL_DIALOG_CONTROL",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-artifact",
		bool_value: true,
	  },
	  {
		action: "SET_HEX_EDITOR_CONTROL",
		bool_value: true,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "current-chapter",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-birthday",
		bool_value: true,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 1,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-map",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-artifact",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "man",
		argument: "map",
		script: "man-map",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "map",
		script: "command-map",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "man",
		argument: "parts",
		script: "man-parts",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "parts",
		script: "command-parts",
	  },
	  {
		is_fail: true,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "parts",
		script: "command-parts-fail",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MONITOR",
		script: "command-parts-monitor",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HEAT SINK",
		script: "command-parts-heatsink",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HEATSINK",
		script: "command-parts-heatsink",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "POWER SUPPLY",
		script: "command-parts-powersupply",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "POWERSUPPLY",
		script: "command-parts-powersupply",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "KEYBOARD",
		script: "command-parts-keyboard",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MOUSE",
		script: "command-parts-mouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARD DRIVE",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARDDRIVE",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARD DISK",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARDDISK",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HDD",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "PLATE",
		script: "command-parts-plate",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "DINNER PLATE",
		script: "command-parts-plate",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "NEEDLE",
		script: "command-parts-needle",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "PHONOGRAPH NEEDLE",
		script: "command-parts-needle",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "RAM CHIPS",
		script: "command-parts-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "RAMCHIPS",
		script: "command-parts-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "RAM",
		script: "command-parts-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "CLOCK",
		script: "command-parts-clock",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "CPU",
		script: "command-parts-cpu",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "GOLDFISH",
		script: "command-parts-goldfish",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "ABACUS",
		script: "command-parts-abacus",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MAINFRAME OS",
		script: "command-parts-os",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MAINFRAMEOS",
		script: "command-parts-os",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "OS",
		script: "command-parts-os",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "OPERATINGSYSTEM",
		script: "command-parts-os",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-toot-done",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 1,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-monitor",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "monitor",
		script: "look-monitor",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cactuscooler-delivered",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-cactuscooler-castle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-heatsink",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "heat sink",
		script: "look-heatsink",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-powersupply",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "power supply",
		script: "look-powersupply",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-heatsink",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-heatsink",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "heat sink",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-powersupply",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-powersupply",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "power supply",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-monitor",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-monitor",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "monitor",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-bert-secret",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-lambda-bert-backstory",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-parts-round-2-backstory",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-keyboard",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "keyboard",
		script: "look-keyboard",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-mouse",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "mouse",
		script: "look-mouse",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-needle",
		bool_value: true,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-carrying-plate",
		expected_bool: true,
		jump_index: 113,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 115,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-solder",
		bool_value: true,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 115,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "needle",
		script: "look-needle",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-plate",
		bool_value: true,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-carrying-needle",
		expected_bool: true,
		jump_index: 120,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 122,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-solder",
		bool_value: true,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 122,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "plate",
		script: "look-plate",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-plate",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "plate",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-needle",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "needle",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-solder",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-harddrive",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "hard drive",
		script: "look-harddrive",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-harddrive",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-harddrive",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "hard drive",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-keyboard",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "keyboard",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-mouse",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "mouse",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-bert-message",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-parts-round-3-backstory",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 3,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-seamoss",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-ramchips",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "ram chips",
		script: "look-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "ram",
		script: "look-ramchips",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-clock",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "clock",
		script: "look-clock",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-goldfish",
		bool_value: true,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-carrying-abacus",
		expected_bool: true,
		jump_index: 168,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 170,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-solder",
		bool_value: true,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 170,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "goldfish",
		script: "look-goldfish",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-abacus",
		bool_value: true,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-carrying-goldfish",
		expected_bool: true,
		jump_index: 175,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 177,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-solder",
		bool_value: true,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 177,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "abacus",
		script: "look-abacus",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-goldfish",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "goldfish",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-abacus",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "abacus",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-solder",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-cpu",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "cpu",
		script: "look-cpu",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-ramchips",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "ram chips",
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "ram",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-clock",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "clock",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-cpu",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-cpu",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "cpu",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-last-parts-done",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-warp-granted",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-parts-round-4-backstory",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: true,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 4,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-seen-room-99",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-mainframeos",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-castle99",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-mainframeos",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-mainframeos",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "mainframeos",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-ring-zero-enabled-in-castle",
		bool_value: true,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 5,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "credits-from-menu",
		bool_value: false,
	  },
	  {
		action: "SET_WARP_STATE",
		string: "ch2-ending",
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-castle-outside",
	  },
	],
	"debug-menu-simon": [
	  {
		action: "SET_SERIAL_DIALOG_CONTROL",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-artifact",
		bool_value: true,
	  },
	  {
		action: "SET_HEX_EDITOR_CONTROL",
		bool_value: true,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "current-chapter",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 1,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-map",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-artifact",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "man",
		argument: "map",
		script: "man-map",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "map",
		script: "command-map",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "man",
		argument: "parts",
		script: "man-parts",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "parts",
		script: "command-parts",
	  },
	  {
		is_fail: true,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "parts",
		script: "command-parts-fail",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MONITOR",
		script: "command-parts-monitor",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HEAT SINK",
		script: "command-parts-heatsink",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HEATSINK",
		script: "command-parts-heatsink",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "POWER SUPPLY",
		script: "command-parts-powersupply",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "POWERSUPPLY",
		script: "command-parts-powersupply",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "KEYBOARD",
		script: "command-parts-keyboard",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MOUSE",
		script: "command-parts-mouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARD DRIVE",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARDDRIVE",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARD DISK",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARDDISK",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HDD",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "PLATE",
		script: "command-parts-plate",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "DINNER PLATE",
		script: "command-parts-plate",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "NEEDLE",
		script: "command-parts-needle",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "PHONOGRAPH NEEDLE",
		script: "command-parts-needle",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "RAM CHIPS",
		script: "command-parts-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "RAMCHIPS",
		script: "command-parts-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "RAM",
		script: "command-parts-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "CLOCK",
		script: "command-parts-clock",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "CPU",
		script: "command-parts-cpu",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "GOLDFISH",
		script: "command-parts-goldfish",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "ABACUS",
		script: "command-parts-abacus",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MAINFRAME OS",
		script: "command-parts-os",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MAINFRAMEOS",
		script: "command-parts-os",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "OS",
		script: "command-parts-os",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "OPERATINGSYSTEM",
		script: "command-parts-os",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-toot-done",
		bool_value: true,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-wait-for-hat-touch",
		expected_bool: true,
		jump_index: 55,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 57,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "ch2-wait-for-hat-touch-message",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 57,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-ring-zero-enabled-in-castle",
		expected_bool: false,
		jump_index: 59,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 67,
	  },
	  {
		action: "CHECK_DEBUG_MODE",
		expected_bool: false,
		jump_index: 61,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 66,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "ch2-in-room",
		value: 0,
		jump_index: 63,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 65,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "warp-ch2-town-check-fail-message",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 65,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 66,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 67,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-in-room",
		operation: "SET",
		value: 0,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "current-chapter",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "SET_PLAYER_CONTROL",
		bool_value: false,
	  },
	  {
		action: "SET_SERIAL_DIALOG_CONTROL",
		bool_value: false,
	  },
	  {
		action: "SET_WARP_STATE",
		string: "warping",
	  },
	  {
		action: "SET_ENTITY_TICK_SCRIPT",
		entity: "%PLAYER%",
		script: "spin-quickly",
	  },
	  {
		action: "SCREEN_FADE_OUT",
		color: "#000000",
		duration: 500,
	  },
	  {
		expected_bool: true,
		action: "CHECK_VARIABLE",
		variable: "ch2-storyflag-round",
		comparison: ">=",
		value: 5,
		jump_index: 77,
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-castle-31",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 79,
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-castle-31-doorless",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 79,
	  },
	],
	"debug-hub": [
	  {
		action: "LOAD_MAP",
		map: "warp_zone",
	  },
	],
	system_bell: [
	  {
		action: "SHOW_SERIAL_DIALOG",
		disable_newline: false,
		serial_dialog: "main_menu.mgs:91:2",
	  },
	],
	"debug-bob": [
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-artifact",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-map",
		bool_value: true,
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-bobsclub",
	  },
	],
	"debug-bob2": [
	  {
		action: "SET_WARP_STATE",
		string: "warping",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-artifact",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-map",
		bool_value: true,
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-bobsclub-basement",
	  },
	],
	"debug-bob3": [
	  {
		action: "SET_WARP_STATE",
		string: "warping",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-artifact",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-map",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-bob-party",
		bool_value: true,
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-bobsclub-basement",
	  },
	],
	"debug-king": [
	  {
		action: "SET_SERIAL_DIALOG_CONTROL",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-artifact",
		bool_value: true,
	  },
	  {
		action: "SET_HEX_EDITOR_CONTROL",
		bool_value: true,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "current-chapter",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-birthday",
		bool_value: true,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 1,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-map",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-has-artifact",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "man",
		argument: "map",
		script: "man-map",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "map",
		script: "command-map",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "man",
		argument: "parts",
		script: "man-parts",
	  },
	  {
		is_fail: false,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "parts",
		script: "command-parts",
	  },
	  {
		is_fail: true,
		action: "REGISTER_SERIAL_DIALOG_COMMAND",
		command: "parts",
		script: "command-parts-fail",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MONITOR",
		script: "command-parts-monitor",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HEAT SINK",
		script: "command-parts-heatsink",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HEATSINK",
		script: "command-parts-heatsink",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "POWER SUPPLY",
		script: "command-parts-powersupply",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "POWERSUPPLY",
		script: "command-parts-powersupply",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "KEYBOARD",
		script: "command-parts-keyboard",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MOUSE",
		script: "command-parts-mouse",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARD DRIVE",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARDDRIVE",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARD DISK",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HARDDISK",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "HDD",
		script: "command-parts-harddrive",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "PLATE",
		script: "command-parts-plate",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "DINNER PLATE",
		script: "command-parts-plate",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "NEEDLE",
		script: "command-parts-needle",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "PHONOGRAPH NEEDLE",
		script: "command-parts-needle",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "RAM CHIPS",
		script: "command-parts-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "RAMCHIPS",
		script: "command-parts-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "RAM",
		script: "command-parts-ramchips",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "CLOCK",
		script: "command-parts-clock",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "CPU",
		script: "command-parts-cpu",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "GOLDFISH",
		script: "command-parts-goldfish",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "ABACUS",
		script: "command-parts-abacus",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MAINFRAME OS",
		script: "command-parts-os",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "MAINFRAMEOS",
		script: "command-parts-os",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "OS",
		script: "command-parts-os",
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "parts",
		argument: "OPERATINGSYSTEM",
		script: "command-parts-os",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-toot-done",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 1,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-monitor",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "monitor",
		script: "look-monitor",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cactuscooler-delivered",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-cactuscooler-castle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-heatsink",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "heat sink",
		script: "look-heatsink",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-powersupply",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "power supply",
		script: "look-powersupply",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-heatsink",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-heatsink",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "heat sink",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-powersupply",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-powersupply",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "power supply",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-monitor",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-monitor",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "monitor",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-bert-secret",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-lambda-bert-backstory",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-parts-round-2-backstory",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-keyboard",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "keyboard",
		script: "look-keyboard",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-mouse",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "mouse",
		script: "look-mouse",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-needle",
		bool_value: true,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-carrying-plate",
		expected_bool: true,
		jump_index: 112,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 114,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-solder",
		bool_value: true,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 114,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "needle",
		script: "look-needle",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-plate",
		bool_value: true,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-carrying-needle",
		expected_bool: true,
		jump_index: 119,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 121,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-solder",
		bool_value: true,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 121,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "plate",
		script: "look-plate",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-plate",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "plate",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-needle",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "needle",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-solder",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-harddrive",
		bool_value: true,
	  },
	  {
		action: "REGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "hard drive",
		script: "look-harddrive",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-harddrive",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-harddrive",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "hard drive",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-keyboard",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "keyboard",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-carrying-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-installed-mouse",
		bool_value: true,
	  },
	  {
		action: "UNREGISTER_SERIAL_DIALOG_COMMAND_ARGUMENT",
		command: "look",
		argument: "mouse",
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-bert-message",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-parts-round-3-backstory",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-monitor",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-heatsink",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-powersupply",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-keyboard",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mouse",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-plate",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-needle",
		bool_value: false,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-clock",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-goldfish",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-abacus",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-ramchips",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-map-mainframeos",
		bool_value: false,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflag-round",
		operation: "SET",
		value: 3,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-castle13",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-cutseen-castle14",
		bool_value: true,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "ch2-king-rescued",
		bool_value: true,
	  },
	  {
		action: "SET_WARP_STATE",
		string: "Ch2 King Returns",
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-castle-13",
	  },
	],
	"on_tick-button-to-skip": [
	  {
		expected_bool: true,
		action: "CHECK_FOR_BUTTON_PRESS",
		button_id: "ANY",
		success_script: "handler-skip-splash",
	  },
	],
	"handler-skip-splash": [
	  {
		action: "SET_MAP_TICK_SCRIPT",
		script: "main_menu-fade_in",
	  },
	  {
		action: "RUN_SCRIPT",
		script: "null_script",
	  },
	],
	"on_tick-main_menu": [
	  {
		action: "RUN_SCRIPT",
		script: "on_tick-splash",
	  },
	],
	"on_tick-splash": [
	  {
		action: "SET_HEX_EDITOR_CONTROL",
		bool_value: false,
	  },
	  {
		expected_bool: true,
		action: "CHECK_WARP_STATE",
		string: "from-game",
		success_script: "main_menu-fade_in",
	  },
	  {
		action: "TELEPORT_CAMERA_TO_GEOMETRY",
		geometry: "dc801-center",
	  },
	  {
		action: "SCREEN_FADE_IN",
		color: "#000000",
		duration: 800,
	  },
	  {
		action: "NON_BLOCKING_DELAY",
		duration: 2900,
	  },
	  {
		action: "SCREEN_FADE_OUT",
		color: "#000000",
		duration: 800,
	  },
	  {
		action: "SET_ENTITY_TICK_SCRIPT",
		entity: "%PLAYER%",
		script: "null_script",
	  },
	  {
		action: "RUN_SCRIPT",
		script: "main_menu-fade_in",
	  },
	],
	"main_menu-fade_in": [
	  {
		action: "SET_HEX_EDITOR_CONTROL",
		bool_value: false,
	  },
	  {
		action: "SET_ENTITY_TICK_SCRIPT",
		entity: "%PLAYER%",
		script: "null_script",
	  },
	  {
		action: "TELEPORT_CAMERA_TO_GEOMETRY",
		geometry: "menu-center",
	  },
	  {
		action: "SCREEN_FADE_IN",
		color: "#000000",
		duration: 800,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "main_menu",
	  },
	],
	main_menu: [
	  {
		action: "SET_ENTITY_TICK_SCRIPT",
		entity: "%PLAYER%",
		script: "null_script",
	  },
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:165:2",
	  },
	],
	"menu-credits-choice": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:179:2",
	  },
	],
	"menu-credits": [
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "credits-from-menu",
		bool_value: true,
	  },
	  {
		action: "LOAD_MAP",
		map: "credits",
	  },
	],
	"menu-credits2": [
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "credits-from-menu",
		bool_value: true,
	  },
	  {
		action: "LOAD_MAP",
		map: "credits2",
	  },
	],
	"menu-bling-mode": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:201:2",
	  },
	],
	"menu-bling-dc801-showcase": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:213:2",
	  },
	],
	"menu-play_game": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:227:2",
	  },
	],
	"menu-erase_save": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:241:2",
	  },
	],
	"menu-erase_save-0": [
	  {
		action: "SLOT_ERASE",
		slot: 0,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-play_game",
	  },
	],
	"menu-erase_save-1": [
	  {
		action: "SLOT_ERASE",
		slot: 1,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-play_game",
	  },
	],
	"menu-erase_save-2": [
	  {
		action: "SLOT_ERASE",
		slot: 2,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-play_game",
	  },
	],
	"menu-load_game": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:268:2",
	  },
	],
	"menu-load_game-0": [
	  {
		action: "SLOT_LOAD",
		slot: 0,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "slot-number",
		operation: "SET",
		value: 0,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-chapter_select-q",
	  },
	],
	"menu-load_game-1": [
	  {
		action: "SLOT_LOAD",
		slot: 1,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "slot-number",
		operation: "SET",
		value: 1,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-chapter_select-q",
	  },
	],
	"menu-load_game-2": [
	  {
		action: "SLOT_LOAD",
		slot: 2,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "slot-number",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-chapter_select-q",
	  },
	],
	"menu-new_game": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:297:2",
	  },
	],
	"menu-new_game-0": [
	  {
		action: "SLOT_ERASE",
		slot: 0,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "slot-number",
		operation: "SET",
		value: 0,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-player-name-q",
	  },
	],
	"menu-new_game-1": [
	  {
		action: "SLOT_ERASE",
		slot: 1,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "slot-number",
		operation: "SET",
		value: 1,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-player-name-q",
	  },
	],
	"menu-new_game-2": [
	  {
		action: "SLOT_ERASE",
		slot: 2,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "slot-number",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-player-name-q",
	  },
	],
	"menu-player-name-q": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:333:2",
	  },
	],
	"menu-player-name-preset1": [
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Red",
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-player-name-confirm",
	  },
	],
	"menu-player-name-preset2": [
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Bubbles",
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-player-name-confirm",
	  },
	],
	"menu-player-name-preset3": [
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Black Mage",
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-player-name-confirm",
	  },
	],
	"menu-player-name-confirm": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:357:2",
	  },
	],
	"menu-player-name-random": [
	  {
		action: "MUTATE_VARIABLE",
		variable: "random-name-count",
		operation: "RNG",
		value: 20,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 1,
		jump_index: 22,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 2,
		jump_index: 24,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 3,
		jump_index: 26,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 4,
		jump_index: 28,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 5,
		jump_index: 30,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 6,
		jump_index: 32,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 7,
		jump_index: 34,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 8,
		jump_index: 36,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 9,
		jump_index: 38,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 10,
		jump_index: 40,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 11,
		jump_index: 42,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 12,
		jump_index: 44,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 13,
		jump_index: 46,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 14,
		jump_index: 48,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 15,
		jump_index: 50,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 16,
		jump_index: 52,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 17,
		jump_index: 54,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 18,
		jump_index: 56,
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "random-name-count",
		value: 19,
		jump_index: 58,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Bub",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Chara",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Buster",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Tidus",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Frisk",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Farnsworth",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Cloud",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Ash",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Crono",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Terra",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Kremit",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Zidane",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Cecil",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Squall",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Roxas",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Steamed Hams",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Spy",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Tom Honks",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "VeeVee",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "XDDCC",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 60,
	  },
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:412:2",
	  },
	],
	"menu-player-name-reset": [
	  {
		action: "SET_ENTITY_NAME",
		entity: "%PLAYER%",
		string: "Bub",
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-player-name-q",
	  },
	],
	"start-new-game-with-name": [
	  {
		action: "SLOT_SAVE",
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-chapter_select-q",
	  },
	],
	"menu-chapter_select-q": [
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "SET",
		value: 0,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-catwork",
		expected_bool: true,
		jump_index: 3,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 5,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 5,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-shepherd",
		expected_bool: true,
		jump_index: 7,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 9,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 9,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-bender",
		expected_bool: true,
		jump_index: 11,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 13,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 13,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-baker",
		expected_bool: true,
		jump_index: 15,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 17,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 17,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-bobmoss",
		expected_bool: true,
		jump_index: 19,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 21,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 21,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-bea1",
		expected_bool: true,
		jump_index: 23,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 25,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 25,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-trekkie",
		expected_bool: true,
		jump_index: 27,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 29,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 29,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-sportskid",
		expected_bool: true,
		jump_index: 31,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 33,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 33,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-verthandi",
		expected_bool: true,
		jump_index: 35,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 37,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 37,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-bea2",
		expected_bool: true,
		jump_index: 39,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 41,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 41,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "storyflag-rake",
		expected_bool: true,
		jump_index: 43,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 45,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch1-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 45,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "SET",
		value: 0,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-heatsink",
		expected_bool: true,
		jump_index: 48,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 50,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 50,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-powersupply",
		expected_bool: true,
		jump_index: 52,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 54,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 54,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-monitor",
		expected_bool: true,
		jump_index: 56,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 58,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 58,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-harddrive",
		expected_bool: true,
		jump_index: 60,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 62,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 62,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-keyboard",
		expected_bool: true,
		jump_index: 64,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 66,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 66,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-mouse",
		expected_bool: true,
		jump_index: 68,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 70,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 70,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-ramchips",
		expected_bool: true,
		jump_index: 72,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 74,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 74,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-clock",
		expected_bool: true,
		jump_index: 76,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 78,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 78,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-cpu",
		expected_bool: true,
		jump_index: 80,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 82,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 82,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-installed-mainframeos",
		expected_bool: true,
		jump_index: 84,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 86,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "ch2-storyflags-tally",
		operation: "ADD",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 86,
	  },
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:438:2",
	  },
	],
	"menu-chapter_select-1": [
	  {
		action: "MUTATE_VARIABLE",
		variable: "current-chapter",
		operation: "SET",
		value: 1,
	  },
	  {
		action: "LOAD_MAP",
		map: "main",
	  },
	],
	"menu-chapter_select-2-check": [
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch1_finished",
		expected_bool: true,
		jump_index: 5,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "warned_ch1_incomplete",
		expected_bool: true,
		jump_index: 5,
	  },
	  {
		action: "SET_SAVE_FLAG",
		save_flag: "warned_ch1_incomplete",
		bool_value: true,
	  },
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:459:3",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 7,
	  },
	  {
		action: "RUN_SCRIPT",
		script: "menu-chapter_select-2",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 7,
	  },
	],
	"menu-chapter_select-2": [
	  {
		action: "MUTATE_VARIABLE",
		variable: "current-chapter",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "CHECK_SAVE_FLAG",
		save_flag: "ch2-cutseen-birthday",
		expected_bool: false,
		jump_index: 3,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 5,
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-magehouse-birthday",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 5,
	  },
	  {
		action: "SET_WARP_STATE",
		string: "raw_game_load-ch2",
	  },
	  {
		expected_bool: true,
		comparison: "==",
		action: "CHECK_VARIABLE",
		variable: "playersave-room",
		value: 1,
		jump_index: 9,
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-town",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 15,
	  },
	  {
		expected_bool: true,
		action: "CHECK_VARIABLE",
		variable: "ch2-storyflag-round",
		comparison: ">=",
		value: 5,
		jump_index: 12,
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-castle-1",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 14,
	  },
	  {
		action: "LOAD_MAP",
		map: "ch2-castle-1-doorless",
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 14,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 15,
	  },
	],
	"menu-save_game": [
	  {
		action: "SHOW_DIALOG",
		dialog: "main_menu.mgs:485:2",
	  },
	],
	"menu-save_game-yes": [
	  {
		inbound: true,
		action: "COPY_VARIABLE",
		entity: "%PLAYER%",
		field: "x",
		variable: "playersave-x",
	  },
	  {
		inbound: true,
		action: "COPY_VARIABLE",
		entity: "%PLAYER%",
		field: "y",
		variable: "playersave-y",
	  },
	  {
		action: "MUTATE_VARIABLES",
		variable: "playersave-room",
		operation: "SET",
		source: "ch2-in-room",
	  },
	  {
		expected_bool: true,
		action: "CHECK_ENTITY_DIRECTION",
		entity: "%PLAYER%",
		direction: "north",
		jump_index: 8,
	  },
	  {
		expected_bool: true,
		action: "CHECK_ENTITY_DIRECTION",
		entity: "%PLAYER%",
		direction: "east",
		jump_index: 10,
	  },
	  {
		expected_bool: true,
		action: "CHECK_ENTITY_DIRECTION",
		entity: "%PLAYER%",
		direction: "south",
		jump_index: 12,
	  },
	  {
		expected_bool: true,
		action: "CHECK_ENTITY_DIRECTION",
		entity: "%PLAYER%",
		direction: "west",
		jump_index: 14,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 16,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "playersave-dir",
		operation: "SET",
		value: 0,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 16,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "playersave-dir",
		operation: "SET",
		value: 1,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 16,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "playersave-dir",
		operation: "SET",
		value: 2,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 16,
	  },
	  {
		action: "MUTATE_VARIABLE",
		variable: "playersave-dir",
		operation: "SET",
		value: 3,
	  },
	  {
		action: "GOTO_ACTION_INDEX",
		action_index: 16,
	  },
	  {
		action: "SLOT_SAVE",
	  },
	  {
		action: "SET_ENTITY_INTERACT_SCRIPT",
		entity: "%SELF%",
		script: "menu-save_game",
	  },
	],
	"menu-save_game-no": [
	  {
		action: "SET_ENTITY_INTERACT_SCRIPT",
		entity: "%SELF%",
		script: "menu-save_game",
	  },
	],
	"menu-save_game-main_menu": [
	  {
		action: "SET_WARP_STATE",
		string: "from-game",
	  },
	  {
		action: "LOAD_MAP",
		map: "main_menu",
	  },
	],
};

module.exports = {
	scripts,
}
